baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "我的网站"

defaultContentLanguage = "zh-cn"

disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[module]
  [[module.imports]]
    path = "minimal-theme"

